import type { TravelPackage } from '../types';

export const EXPLORE_PACKAGES: TravelPackage[] = [
  {
    id: 'pkg-1',
    category: 'tours',
    title: 'Burj Khalifa At The Top Level 124 & 125 Entry',
    subtitle: 'Fast-track access with panoramic skyline views',
    location: 'Dubai, UAE',
    badge: 'Bestseller',
    price: '$46.00',
    rating: 4.9,
    reviews: '85k+ booked',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://klook.tp.st/',
    provider: 'klook',
  },
  {
    id: 'pkg-2',
    category: 'esims',
    title: 'Asia Regional 10GB 5G High-Speed eSIM',
    subtitle: 'Works across 18 Asian countries seamlessly',
    location: 'Singapore, Thailand, Malaysia +15',
    badge: 'Instant QR',
    price: '$18.50',
    rating: 4.9,
    reviews: '120k+ users',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://airalo.tp.st/',
    provider: 'airalo',
  },
  {
    id: 'pkg-3',
    category: 'flights',
    title: 'Direct & Secret Connected Flight Routes',
    subtitle: 'Smart routing algorithm for guaranteed cheapest fare',
    location: 'Bangkok (BKK) ➔ Singapore (SIN)',
    badge: 'Fare Drop 35%',
    price: '$68.00',
    rating: 4.7,
    reviews: 'Kiwi Nomad Live',
    imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://kiwi.tp.st/',
    provider: 'kiwi',
  },
  {
    id: 'pkg-4',
    category: 'tours',
    title: 'Louvre Museum Paris Skip-The-Line Pass',
    subtitle: 'Priority dedicated timeslot entrance + Audio Guide',
    location: 'Paris, France',
    badge: 'Official Ticket',
    price: '$24.00',
    rating: 4.8,
    reviews: '64k+ booked',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://tiqets.tp.st/',
    provider: 'tiqets',
  },
  {
    id: 'pkg-5',
    category: 'tours',
    title: 'Universal Studios Singapore 1-Day Express Pass',
    subtitle: 'All zones unrestricted admission voucher',
    location: 'Sentosa, Singapore',
    badge: 'Instant Voucher',
    price: '$62.00',
    rating: 4.9,
    reviews: '92k+ booked',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://klook.tp.st/',
    provider: 'klook',
  },
  {
    id: 'pkg-6',
    category: 'esims',
    title: 'Europe 39 Countries 20GB Data eSIM',
    subtitle: 'Zero roaming charges with ultra-low latency 5G',
    location: 'UK, France, Germany, Italy +35',
    badge: 'Popular',
    price: '$32.00',
    rating: 4.9,
    reviews: '210k+ users',
    imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://airalo.tp.st/',
    provider: 'airalo',
  },
  {
    id: 'pkg-7',
    category: 'flights',
    title: 'Transatlantic & Regional Open-Jaw Flight Deals',
    subtitle: 'Multi-city combinations with Kiwi Guarantee protection',
    location: 'London (LHR) ➔ New York (JFK)',
    badge: 'Save $180',
    price: '$285.00',
    rating: 4.8,
    reviews: 'Kiwi Verified',
    imageUrl: 'https://images.unsplash.com/photo-1500835556837-99ac94a94552?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://kiwi.tp.st/',
    provider: 'kiwi',
  },
  {
    id: 'pkg-8',
    category: 'tours',
    title: 'Colosseum, Roman Forum & Palatine Hill Priority',
    subtitle: 'Direct mobile barcode entry with arena floor option',
    location: 'Rome, Italy',
    badge: 'Must Visit',
    price: '$29.50',
    rating: 4.8,
    reviews: '55k+ booked',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://tiqets.tp.st/',
    provider: 'tiqets',
  },
  {
    id: 'pkg-9',
    category: 'stays',
    title: 'Marina Bay Waterfront Luxury Suites',
    subtitle: 'Infinity pool access with skyline breakfast package',
    location: 'Marina Bay, Singapore',
    badge: 'Special Rate',
    price: '$240.00',
    rating: 4.9,
    reviews: 'Top Pick',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://klook.tp.st/',
    provider: 'klook',
  },
  {
    id: 'pkg-10',
    category: 'tours',
    title: 'Mount Fuji & Hakone Day Tour with Cruise',
    subtitle: 'Bullet train return option & English tour guide',
    location: 'Tokyo, Japan',
    badge: 'Free Cancellation',
    price: '$78.00',
    rating: 4.9,
    reviews: '48k+ booked',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    partnerUrl: 'https://klook.tp.st/',
    provider: 'klook',
  },
];
