export interface PartnerBrand {
  id: string;
  name: string;
  category: 'flights' | 'esim' | 'transfer' | 'rental' | 'tours' | 'insurance' | 'compensation' | 'services';
  logoText: string;
  tagline: string;
  commissionBadge: string;
  cookieLifetime: string;
  url: string;
  description: string;
  bgImage: string;
}

export const MONETIZED_BRANDS: PartnerBrand[] = [
  // 1. Flights & Airfare
  {
    id: 'aviasales',
    name: 'Aviasales',
    category: 'flights',
    logoText: 'AVIASALES',
    tagline: 'Meta Flight Search Engine',
    commissionBadge: '40% Mega Yield',
    cookieLifetime: '30 days',
    url: 'https://aviasales.tpm.lv/Ku6jysJy',
    description: 'Compare multi-airline flight routes and uncover lowest base fares across international routes.',
    bgImage: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'kiwi',
    name: 'Kiwi.com',
    category: 'flights',
    logoText: 'KIWI.COM',
    tagline: 'Virtual Interlining Flights',
    commissionBadge: '3% + Guarantee',
    cookieLifetime: '30 days',
    url: 'https://www.kiwi.com',
    description: 'Unique multi-carrier route hacks with missed flight protection guarantee.',
    bgImage: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?q=80&w=800&auto=format&fit=crop',
  },

  // 2. eSIM & Mobile Connectivity
  {
    id: 'yesim',
    name: 'Yesim',
    category: 'esim',
    logoText: 'YESIM',
    tagline: 'Global Unlimited 5G eSIM',
    commissionBadge: '18% High Yield',
    cookieLifetime: '90 days',
    url: 'https://yesim.tpm.lv/iV7xxxWO',
    description: 'Swiss-grade pay-as-you-go and unlimited eSIM data coverage across 150+ countries.',
    bgImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'airalo',
    name: 'Airalo',
    category: 'esim',
    logoText: 'AIRALO',
    tagline: 'Premier Global eSIM Store',
    commissionBadge: '12% Top Trending',
    cookieLifetime: '30 days',
    url: 'https://airalo.tpm.lv/VFoS8l4O',
    description: 'Digital prepaid local, regional, and global eSIM packages with instant QR setup.',
    bgImage: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'saily',
    name: 'Saily',
    category: 'esim',
    logoText: 'SAILY',
    tagline: 'NordVPN-Powered Travel eSIM',
    commissionBadge: '15% Reward',
    cookieLifetime: '30 days',
    url: 'https://saily.com',
    description: 'Secure, privacy-first mobile connectivity created by the cybersecurity experts at Nord Security.',
    bgImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'gigsky',
    name: 'GigSky',
    category: 'esim',
    logoText: 'GIGSKY',
    tagline: 'Cruise & Flight Offshore eSIM',
    commissionBadge: '20% High Payout',
    cookieLifetime: '30 days',
    url: 'https://www.gigsky.com',
    description: 'Exclusive in-flight, cruise ship, and global land data roaming for frequent flyers.',
    bgImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'drimsim',
    name: 'Drimsim',
    category: 'esim',
    logoText: 'DRIMSIM',
    tagline: 'Real Universal SIM & eSIM',
    commissionBadge: '€8 Flat Reward',
    cookieLifetime: '90 days',
    url: 'https://drimsim.com',
    description: 'The universal SIM that charges raw local carrier rates per megabyte without package lock-in.',
    bgImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=800&auto=format&fit=crop',
  },

  // 3. Airport Transfers & Rides
  {
    id: 'kiwitaxi',
    name: 'Kiwitaxi',
    category: 'transfer',
    logoText: 'KIWITAXI',
    tagline: 'Global Airport Pickup',
    commissionBadge: '9-11% Payout',
    cookieLifetime: '30 days',
    url: 'https://kiwitaxi.com',
    description: 'Door-to-door private transfers with meet-and-greet arrival services in 100+ nations.',
    bgImage: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'gettransfer',
    name: 'GetTransfer',
    category: 'transfer',
    logoText: 'GETTRANSFER',
    tagline: 'Bidding Ride & VIP Chauffeur',
    commissionBadge: '4-25% Yield',
    cookieLifetime: '30 days',
    url: 'https://gettransfer.tpm.lv/5pqXzINW',
    description: 'Reverse-auction vehicle marketplace saving travelers up to 30% against metered airport cabs.',
    bgImage: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'welcomepickups',
    name: 'Welcome Pickups',
    category: 'transfer',
    logoText: 'WELCOME PICKUPS',
    tagline: 'Personalized City Transfers',
    commissionBadge: '8-9% Reward',
    cookieLifetime: '45 days',
    url: 'https://www.welcomepickups.com',
    description: 'English-speaking drivers, curated city introductions, and flight monitoring pickups.',
    bgImage: 'https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'intuitravel',
    name: 'intui.travel',
    category: 'transfer',
    logoText: 'INTUI.TRAVEL',
    tagline: 'Resort & Airport Shuttles',
    commissionBadge: '10% Return',
    cookieLifetime: '35 days',
    url: 'https://www.intui.travel',
    description: 'Seamless hotel shuttle vans and executive airport limousines in 175 countries.',
    bgImage: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop',
  },

  // 4. Car & Bike Rentals
  {
    id: 'qeeq',
    name: 'QEEQ',
    category: 'rental',
    logoText: 'QEEQ',
    tagline: 'Price Drop Protected Car Hire',
    commissionBadge: '5-10% Reward',
    cookieLifetime: '30 days',
    url: 'https://qeeq.tpm.lv/74r6KKCl',
    description: 'Global car rentals featuring automatic price drop refunds if vehicle rates drop before pickup.',
    bgImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'getrentacar',
    name: 'GetRentacar',
    category: 'rental',
    logoText: 'GETRENTACAR',
    tagline: 'Local Host & Luxury Cars',
    commissionBadge: '10% High Rate',
    cookieLifetime: '90 days',
    url: 'https://getrentacar.tpm.lv/R6UQKZxY',
    description: 'Book vehicles directly from verified local owners and commercial fleets with flexible deposits.',
    bgImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'localrent',
    name: 'Localrent',
    category: 'rental',
    logoText: 'LOCALRENT',
    tagline: 'No-Deposit Small Fleet Cars',
    commissionBadge: '7.5-10% Payout',
    cookieLifetime: '30 days',
    url: 'https://localrent.com',
    description: 'Transparent car rentals from local independent companies with low or zero security deposits.',
    bgImage: 'https://images.unsplash.com/photo-1485291571180-61609ec78fb3?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'economybookings',
    name: 'EconomyBookings',
    category: 'rental',
    logoText: 'ECONOMYBOOKINGS',
    tagline: 'Discounted Worldwide Fleets',
    commissionBadge: '3-8% Reward',
    cookieLifetime: '30 days',
    url: 'https://www.economybookings.com',
    description: 'Compare 800+ trusted rental brands including Hertz, Sixt, Europcar, and Avis in one search.',
    bgImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'autoeurope',
    name: 'AutoEurope',
    category: 'rental',
    logoText: 'AUTOEUROPE',
    tagline: 'Europe & UK Fleet Leader',
    commissionBadge: '4.4-8% Yield',
    cookieLifetime: '30 days',
    url: 'https://www.autoeurope.com',
    description: 'Trusted European road trip provider with zero cancellation fees up to 48 hours before pickup.',
    bgImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'bikesbooking',
    name: 'BikesBooking',
    category: 'rental',
    logoText: 'BIKESBOOKING',
    tagline: 'Scooters, Motos & Bicycles',
    commissionBadge: '4% Specialized',
    cookieLifetime: '30 days',
    url: 'https://bikesbooking.com',
    description: 'Online booking service for motorcycles, mopeds, bicycles, and quad bikes around the world.',
    bgImage: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=800&auto=format&fit=crop',
  },

  // 5. Tours, Activities & Experiences
  {
    id: 'wegotrip',
    name: 'WeGoTrip',
    category: 'tours',
    logoText: 'WEGOTRIP',
    tagline: 'Self-Guided Audio Excursions',
    commissionBadge: 'Up to 41.5% Yield',
    cookieLifetime: '30 days',
    url: 'https://wegotrip.tpm.lv/XHAJvX8I',
    description: 'Audio tours with museum tickets created by local historians, guides, and cultural experts.',
    bgImage: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'klook',
    name: 'Klook',
    category: 'tours',
    logoText: 'KLOOK',
    tagline: 'Asia & World Experiences',
    commissionBadge: '2-5% Best Seller',
    cookieLifetime: '30 days',
    url: 'https://www.klook.com',
    description: 'Verified tickets to Disneyland, Universal Studios, JR rail passes, and island diving excursions.',
    bgImage: 'https://images.unsplash.com/photo-1513415564515-763d91423bdd?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'tiqets',
    name: 'Tiqets',
    category: 'tours',
    logoText: 'TIQETS',
    tagline: 'Museums & Iconic Monuments',
    commissionBadge: '3.5-8% Direct Entry',
    cookieLifetime: '30 days',
    url: 'https://www.tiqets.com',
    description: 'Skip long ticket lines at the Louvre, Sagrada Familia, Colosseum, and Burj Khalifa.',
    bgImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'gocity',
    name: 'Go City',
    category: 'tours',
    logoText: 'GO CITY',
    tagline: 'All-Inclusive Multi-Attraction Pass',
    commissionBadge: '3.4-6% Pass Rate',
    cookieLifetime: '90 days',
    url: 'https://gocity.com',
    description: 'Save up to 50% on top city attractions with one digital pass across New York, London, Paris, and Singapore.',
    bgImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'kkday',
    name: 'KKday',
    category: 'tours',
    logoText: 'KKDAY',
    tagline: 'Asian Day Tours & Rail Passes',
    commissionBadge: '1-5% Regional Top',
    cookieLifetime: '30 days',
    url: 'https://www.kkday.com',
    description: 'Curated travel experiences, airport SIMs, bullet train tickets, and outdoor excursions.',
    bgImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
  },

  // 6. Travel Insurance
  {
    id: 'ekta',
    name: 'EKTA',
    category: 'insurance',
    logoText: 'EKTA',
    tagline: 'Global COVID & Injury Insurance',
    commissionBadge: '25% High Yield',
    cookieLifetime: '30 days',
    url: 'https://ektatraveling.tpm.lv/rMJ2GOQx',
    description: 'Worldwide medical coverage for travelers from 2 months to 100 years old with 24/7 multilingual support.',
    bgImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop',
  },

  // 7. Flight Delay & Compensation Claims
  {
    id: 'airhelp',
    name: 'AirHelp',
    category: 'compensation',
    logoText: 'AIRHELP',
    tagline: 'Up to $650 Delayed Flight Claim',
    commissionBadge: '15-16.6% Payout',
    cookieLifetime: '45 days',
    url: 'https://airhelp.tpm.lv/epi3jZ5Y',
    description: 'World-leading flight compensation specialists. Claim up to $650 (€600) for delayed or canceled flights.',
    bgImage: 'https://images.unsplash.com/photo-1540339832862-474599807836?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'compensair',
    name: 'Compensair',
    category: 'compensation',
    logoText: 'COMPENSAIR',
    tagline: 'Zero-Risk Flight Claim Service',
    commissionBadge: '€5-12 Flat Bounty',
    cookieLifetime: '30 days',
    url: 'https://compensair.tpm.lv/ka8qEeoG',
    description: 'Get compensated for flight delays, cancellations, and denied boarding under EU and UK law.',
    bgImage: 'https://images.unsplash.com/photo-1483450388369-9ed95738483c?q=80&w=800&auto=format&fit=crop',
  },

  // 8. Luggage & Storage Utility
  {
    id: 'radicalstorage',
    name: 'Radical Storage',
    category: 'services',
    logoText: 'RADICAL STORAGE',
    tagline: 'Secure City Luggage Network',
    commissionBadge: '8% Return',
    cookieLifetime: '30 days',
    url: 'https://radicalstorage.com',
    description: 'Store bags safely for €5/day at verified hotels, bars, and cafes in 500+ major transit cities.',
    bgImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800&auto=format&fit=crop',
  },
];
